"""created relationship

Revision ID: 1736759492df
Revises: b4b0523dd8b3
Create Date: 2019-07-02 14:08:33.112741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1736759492df'
down_revision = 'b4b0523dd8b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch'], ['id'])
    op.add_column('pitches', sa.Column('users_id', sa.Integer(), nullable=True))
    op.drop_constraint('pitches_user_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'user', ['users_id'], ['id'])
    op.drop_column('pitches', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_user_id_fkey', 'pitches', 'user', ['user_id'], ['id'])
    op.drop_column('pitches', 'users_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'pitch')
    # ### end Alembic commands ###
