"""aadded columns

Revision ID: fbb37c807e73
Revises: c4412d4fc69c
Create Date: 2019-07-02 11:23:50.203138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb37c807e73'
down_revision = 'c4412d4fc69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('pitch_category', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'author')
    op.drop_column('pitches', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'pitch_category')
    op.drop_column('pitches', 'pitch')
    # ### end Alembic commands ###
